### ISSUE TITLE
How exactly I can run the application?

### ISSUE THREAD

**Issue by Sid1337** [LasCC/HackTools#26]
I'm getting an error like below attached screenshot. Could you please explain how can I run it ?

<img width="325" alt="image" src="https://user-images.githubusercontent.com/11360205/85714574-23c0e480-b71d-11ea-8b6e-b3b3b7d872bc.png">

**Comment by LasCC** [comment]
Hi there ! 

Thank you for using our app, I updated the readme and created a tutorial sorry for the inconvenience.
