### ISSUE TITLE
Semantic versioning for releases

### ISSUE THREAD

**Issue by someshkar** [LasCC/HackTools#50]
At the moment, loading Hack-Tools in my Chromium based browser throws an error with the version number defined in the `manifest.json` file, specifically because the version is `0.1.2b`. This is what the file looks like at the moment (as of [this release](https://github.com/LasCC/Hack-Tools/releases/tag/0.1.2)):

```json
{
  "name": "Hack Tools",
  "version": "0.1.2b",
  "description": "The all in one Red team extension for web pentester",
  "browser_action": {
    "default_title": "Hack Tools",
    "default_popup": "index.html",
    "default_icon": {
      "16": "get_started16.png",
      "32": "get_started32.png",
      "48": "get_started48.png",
      "128": "get_started128.png"
    }
  },
  "icons": {
    "16": "get_started16.png",
    "32": "get_started32.png",
    "48": "get_started48.png",
    "128": "get_started128.png"
  },
  "manifest_version": 2,
  "devtools_page": "devtools.html"
}
```

Switching `0.1.2b` to `0.1.2` manually seemed to fix the issue for me, and it'd be great if this change could be incorporated in the next release too.

**Comment by rb-x** [comment]
Thank you @someshkarfor for reporting the manifest issue, I added the 0.1.2b to make the extension valid for the mozilla plugin store, but I didn't know it caused an error for the chromium browser.
- i fixed the new release for chromium.

**Comment by someshkar** [comment]
@rb-x Sounds great, thanks!
