### ISSUE TITLE
Add Windows commands

### ISSUE THREAD

**Issue by fastlorenzo** [LasCC/HackTools#75]
First of all, this tool looks really nice, good job there!

I think it would be good to have an `Useful Windows commands` (similar to the Linux one)

My .2 😄

**Comment by rb-x** [comment]
Excellent idea @fastlorenzo,
i will try to add some powershell reverse tcp payload and powershell enumeration script in the next version.
You are more than welcome to contribute or atleast give us an idea of what kind of commands/scripts you personally found useful as a read teamer.
Thank you :)
