### ISSUE TITLE
A little off topic

### ISSUE THREAD

**Issue by devxan** [LasCC/HackTools#77]
![image](https://user-images.githubusercontent.com/57809064/103464839-b7d2c080-4ceb-11eb-8223-e106291c5759.png)
How did you change the colors of google chrome like in the images above? Is there an extension for this? @LasCC @rb-x (If those screenshots were taken in some other browser, I am sorry for asking.)

**Comment by LasCC** [comment]
Hi there!

The browser that I'm using in the images is Brave you can download it there -> (https://brave.com/)

**Comment by devxan** [comment]
Ok, thanks!
