### ISSUE TITLE
npm run build Can't resolve bugs

### ISSUE THREAD

**Issue by supernaruto16** [LasCC/HackTools#93]
+ Hi, I ran into 2 errors when build it locally with npm run build
```
ERROR in ./src/components/LayoutApp.js
Module not found: Error: Can't resolve './file_transfer/File_transfer' in '/home/madscientist/Documents/CTFTools/chrome-extensions/Hack-Tools/src/components'
 @ ./src/components/LayoutApp.js 19:0-57 104:20-32
 @ ./src/App.js

ERROR in ./src/components/FeedRSS.js
Module not found: Error: Can't resolve './rss/Cve' in '/home/madscientist/Documents/CTFTools/chrome-extensions/Hack-Tools/src/components'
 @ ./src/components/FeedRSS.js 8:0-28 103:24-27 116:26-29
 @ ./src/components/LayoutApp.js
 @ ./src/App.js
```
+ Then i found it's caused by 2 typing errors
```
./src/components/LayoutApp.js:19: import FileTransfer from "./file_transfer/File_transfer";
=> should be "./file_transfer/file_transfer"
./src/components/FeedRSS.js:8: import cve from './rss/Cve';
=> should be "./rss/cve"
```
+ Btw, the command to build locally with npm in README.md should be
```
npm install && npm run build
```
+ Hope u will fix those on git version

**Comment by jayluxferro** [comment]
Hi @supernaruto16 , I did `npm run build` and I got no errors. What OS and npm version are you using? My environment is macOS and the npm version I'm using is 6.14.10

**Comment by supernaruto16** [comment]
Hi, my environment is Ubuntu 20.04.1 and npm 6.14.11, but i don't think environment is related to the bugs. I think the reason is syntax error in  those js code above.

**Comment by supernaruto16** [comment]
+ These lines on the latest master branch
https://github.com/LasCC/Hack-Tools/blob/83be67d23a31fa143a5ed035bb7667454026c593/src/components/FeedRSS.js#L8
https://github.com/LasCC/Hack-Tools/blob/83be67d23a31fa143a5ed035bb7667454026c593/src/components/LayoutApp.js#L19

**Comment by jayluxferro** [comment]
I just tested the build on linux and  figured out the issue. npm imports on macOS seems to be case insensitive, which makes it  work. You can submit a pull request for the bug and also the README. Just rename the files to **Cve** and **File_transfer** respectively.

Thanks.
